version: "3.8"

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - ./usr/src/app/node_modules
    command: npm run start:dev
    environment:
      DATABASE_URL: postgres://admin:test@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
    ports:
      - "8080:3000"

  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test
      POSTGRES_DB: db

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
    depends_on:
      - postgres

  mongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"